- name: "Verifying valid operating system family: RedHat, Suse, or Debian"
  assert:
    that: ansible_os_family == 'RedHat' or 
          ansible_os_family == 'Suse' or 
          ansible_os_family == 'Debian'
- name: "Verifying ibmmq_package variable is defined"
  assert:
    that:
      - "{{ ibmmq_package }} is defined"
      - "{{ ibmmq_package }} | length > 0"
      - "{{ ibmmq_package }} != None"
- name: "Creating install directory {{ibmmq_install_path}}"
  become: yes
  file:
    path: "{{ ibmmq_install_path }}"
    state: directory
    mode: 0754
- name: "Extracting package to {{ ibmmq_install_path }}"
  become: yes
  unarchive:
    src: "{{ ibmmq_package }}"
    dest: "{{ ibmmq_install_path }}"
- name: Accepting IBM MQ license
  become: yes
  command: "{{ ibmmq_install_path }}/MQServer/mqlicense.sh -accept"